version: "3.9"

services:
  docai-redis:
    image: redis:7-alpine
    container_name: docai-redis
    ports: [ "6379:6379" ]
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped

  docai-minio:
    image: quay.io/minio/minio:latest
    container_name: docai-minio
    command: server /data --address ":9000" --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_BROWSER: "on"
    ports:
      - "9000:9000"   # API
      - "9001:9001"   # Console
    volumes:
      - ./_data/minio:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 5s
      timeout: 3s
      retries: 30
    restart: unless-stopped

  docai-extract-api:
    container_name: docai-extract-api
    build:
      context: .
      target: dev
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload
    ports: [ "8080:8080" ]
    environment:
      REDIS_URL: redis://docai-redis:6379/0
      MINIO_ENDPOINT: docai-minio:9000   # internal address
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      MINIO_BUCKET: docai-extract
      MINIO_REGION: us-east-1
    volumes:
      - ./:/app
    depends_on:
      docai-redis:
        condition: service_healthy
      docai-minio:
        condition: service_healthy
    restart: unless-stopped

  docai-worker-docs:
    container_name: docai-worker-docs
    build:
      context: .
      target: prod
    command: python -m app.worker.worker --queues docs
    environment:
      REDIS_URL: redis://docai-redis:6379/0
      MINIO_ENDPOINT: docai-minio:9000
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      MINIO_BUCKET: docai-extract
    volumes:
      - ./:/app
    depends_on:
      docai-redis:
        condition: service_healthy
      docai-minio:
        condition: service_healthy
    restart: unless-stopped

  docai-worker-extractions:
    container_name: docai-worker-extractions
    build:
      context: .
      target: prod
    command: python -m app.worker.worker --queues extractions
    environment:
      REDIS_URL: redis://docai-redis:6379/0
      MINIO_ENDPOINT: docai-minio:9000
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      MINIO_BUCKET: docai-extract
    volumes:
      - ./:/app
    depends_on:
      docai-redis:
        condition: service_healthy
      docai-minio:
        condition: service_healthy
    restart: unless-stopped